app/protected/controllers/MemberController.php
<?php

class MemberController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('remove'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','import','index','view'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public function actionRemove($id,$mglist_id,$hash)
	{
	  // check hash is correct
	  // remove member from list
	  $member = Member::model()->findByPk($id);
	  $mglist = Mglist::model()->findByPk($mglist_id);
	  $member->removeFromList($id,$mglist_id);
		$this->render('remove',array(
			'member'=>$member,
			'mglist'=>$mglist,
		));
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new member.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate($id)
	{
		$model=new Member;
		$mglist_id = $id;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Member']))
		{
			$model->attributes=$_POST['Member'];
      $model->status=1;
			$model->created_at =new CDbExpression('NOW()'); 
      $model->modified_at =new CDbExpression('NOW()');                
			if($model->save())
			  $model->addToList($model->id,$mglist_id);
			  $lookup_list = Mglist::model()->findByPk($mglist_id);
			  // to do fetch list address
			  $yg = new Yiigun();
			  $yg->memberAdd($lookup_list['address'],$model->address,$model->name);
				$this->redirect('/mglist/'.$mglist_id);
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Member']))
		{
			$model->attributes=$_POST['Member'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Member');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Member('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Member']))
			$model->attributes=$_GET['Member'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

  /**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionImport($id=0)
	{
	      $model = new Import();
    		$model->mglist_id = $id;
    		// Uncomment the following line if AJAX validation is needed
    		// $this->performAjaxValidation($model);
    		if(isset($_POST['Import']))
    		{
    			$temp_email_list = $_POST['Import']['email_list'];
          include('Mail/RFC822.php');
          $parser = new Mail_RFC822();
          // replace the backslash quotes 
          $tolist=str_replace('\\"','"',$temp_email_list); 
          // split the elements by line and by comma 
          $to_email_array = preg_split ("(\r|\n|,)", $tolist, -1, PREG_SPLIT_NO_EMPTY);
          $num_emails = count ($to_email_array); 
          $temp ='';
          // construct bulk list of new members for mailgun api call
          $json_upload ='[';          
          for ($count = 0; $count < $num_emails && $count <= 500; $count++) 
          {
            $json_upload.='{';
            $toAddress=trim($to_email_array[$count]);
            if ($toAddress<>'') {
              $addresses = $parser->parseAddressList('my group:'.$toAddress,'yourdomain.com', false,true);
              foreach ($addresses as $i) {
                if ($i->mailbox<>'' and $i->host<>'') {
                  $temp.=$i->mailbox.'@'.$i->host.',';
                }
                $m = new Member();
                if ($i->personal<>'') {
                  $m->name = $i->personal;
                  $json_upload.='"name": "'.$m->name.'", ';                  
                }
                else 
                  $m->name ='';
                $m->address=$i->mailbox.'@'.$i->host;
                $json_upload.='"address": "'.$m->address.'"';                  
                $m->status=1;
                $m->created_at = new CDbExpression('NOW()'); 
                $m->modified_at = new CDbExpression('NOW()');          	                  
                 // echo $m->name.' '.$m->address.' ->'.$id.'<br />';
 $lookup_item=Member::model()->findByAttributes(array('address'=>$m->address));
            	  if (!is_null($lookup_item)) {
            	       // member exists
                     // echo 'exists'.$lookup_item['id'];
            	      $m->addToList($lookup_item['id'],$id);
            	  } else {
            	    // new member
                  $m->save();
                  $last_id = Yii::app()->db->getLastInsertID();
                  // echo 'saved'.$last_id;
                  $m->addToList($last_id,$id);
            	  }
              } 
            }
            $json_upload.='},';            
          }      
          $temp=trim($temp,',');
          $model->email_list = $temp;
          $json_upload=trim($json_upload,',');
          $json_upload .=']';
          
    			if($model->save()) {
            Yii::app()->user->setFlash('import_success','Thank you! Your messages have been submitted.');
            $yg = new Yiigun;
            // echo $json_upload;
            $list_item = Mglist::model()->findByPk($id);
            // echo $list_item['address'];
            $yg->memberBulkAdd($list_item['address'],$json_upload);
  				  $this->redirect('/mglist/'.$id);			  
    			}
    		}

    		$this->render('import',array(
    			'model'=>$model,'mglist_id'=>$id,
    		));
	}


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Member::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='member-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

app/protected/controllers/MessageController.php
<?php

class MessageController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	
	public function actionCreate($id = 0)
	{
		$model=new Message;
		$model->mglist_id = $id;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Message']))
		{
			$model->attributes=$_POST['Message'];
			$model->created_at =new CDbExpression('NOW()'); 
      $model->modified_at =new CDbExpression('NOW()');          
			if($model->save()) {
		    Yii::app()->user->setFlash('messageSubmitted','Thank you, your message has been posted.'); 
		    $lookup_item = Mglist::model()->findByPk($model->mglist_id);
		    $yg = new Yiigun;
		     $yg->send_simple_message($lookup_item['address'],$model->subject,$model->body,Yii::app()->params['superuser']);
		    
				$this->redirect('/mglist/index');
			  
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}	

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Message']))
		{
			$model->attributes=$_POST['Message'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Message');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Message('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Message']))
			$model->attributes=$_GET['Message'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Message::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='message-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

app/protected/views/mglist/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'mglist-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textAreaRow($model,'description',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<?php echo $form->textFieldRow($model,'address',array('class'=>'span5','maxlength'=>255, 'hint'=>'Specify the full list email address including your domain name e.g. marketing@yourdomain.com)')); ?>

  <?php echo CHtml::dropdownlist("access_level", 'readonly', array('readonly'=>'Read Only','members'=>'Members','everyone'=>'Everyone'));?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

app/protected/views/mglist/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'address',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textAreaRow($model,'description',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<?php echo $form->textFieldRow($model,'access_level',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'created_at',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'modified_at',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

app/protected/views/mglist/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('address')); ?>:</b>
	<?php echo CHtml::encode($data->address); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('description')); ?>:</b>
	<?php echo CHtml::encode($data->description); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('access_level')); ?>:</b>
	<?php echo CHtml::encode($data->access_level); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('created_at')); ?>:</b>
	<?php echo CHtml::encode($data->created_at); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('modified_at')); ?>:</b>
	<?php echo CHtml::encode($data->modified_at); ?>
	<br />


</div>

app/protected/views/mglist/admin.php
<?php
$this->breadcrumbs=array(
	'Mglists'=>array('index'),
	'Manage',
);

if ($cnt ==0)
  $this->menu=array(
  	array('label'=>'Create a list','url'=>array('create')),
  );
else
$this->menu=array(
  array('label'=>'Send a message','url'=>array('message/create')),
	array('label'=>'Create a list','url'=>array('create')),
);


Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('mglist-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Mailing Lists</h1>
<div class="search-form" style="display:none">
<?php
 $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'mglist-grid',
	'dataProvider'=>$model->search(),
	'type'=>'striped',
	'filter'=>$model,
	'columns'=>array(
    array(
            'type' => 'raw',
            'header' => 'Name',
            'name'=>'name',
            'value' => 'CHtml::link($data->name,array(\'mglist/view\',\'id\'=>$data->id))',
            'htmlOptions'=>array('width'=>'150px')
          ),
          array(
                  'type' => 'raw',
                  'header' => 'Address',
                  'name'=>'address',
                  'value' => 'CHtml::link($data->address,array(\'mglist/view\',\'id\'=>$data->id))',
                  'htmlOptions'=>array('width'=>'150px')
            ),
		'access_level',
		/*
		'created_at',
		'modified_at',
		*/
		array(
		  'htmlOptions'=>array('width'=>'150px'),  		
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'header'=>'Options',
      'template'=>'{send}{manage}{sync}{update}{delete}{subscribe}',
          'buttons'=>array
          (
              'send' => array
              (
                'options'=>array('title'=>'Send'),
                'label'=>'<i class="icon-envelope icon-large" style="margin:5px;"></i>',
                'url'=>'Yii::app()->createUrl("message/create", array("id"=>$data->id))',
              ),
              'manage' => array
              (
              'options'=>array('title'=>'Manage'),
                'label'=>'<i class="icon-list icon-large" style="margin:5px;"></i>',
                'url'=>'Yii::app()->createUrl("mglist/view", array("id"=>$data->id))',
              ),
              'sync' => array
              (
              'options'=>array('title'=>'sync'),
                'label'=>'<i class="icon-refresh icon-large" style="margin:5px;"></i>',
                'url'=>'Yii::app()->createUrl("mglist/syncList", array("id"=>$data->id))',
              ),
              'subscribe' => array
              (
              'options'=>array('title'=>'subscribe form'),
                'label'=>'<i class="icon-user icon-large" style="margin:5px;"></i>',
                'url'=>'Yii::app()->createUrl("request/create", array("id"=>$data->id))',
              ),
          ),			
		),
	),
)); ?>

app/protected/views/mglist/create.php
<?php
$this->breadcrumbs=array(
	'Mglists'=>array('index'),
	'Create',
);
/*
$this->menu=array(
	array('label'=>'Send a message','url'=>array('send')),
	array('label'=>'Create a list','url'=>array('create')),
);
*/
?>

<h1>Create a Mailing List</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

app/protected/views/mglist/index.php
<?php
$this->breadcrumbs=array(
	'Mglists',
);

$this->menu=array(
	array('label'=>'Create Mglist','url'=>array('create')),
	array('label'=>'Manage Mglist','url'=>array('admin')),
);
?>

<h1>Manage Lists</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

app/protected/views/mglist/sync.php
<h2>Synchronizing Your Mailing Lists</h2>
<?php
  echo $result;
?>
<p>Complete</p>

app/protected/views/mglist/update.php
<?php
$this->breadcrumbs=array(
	'Mglists'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

/*
$this->menu=array(
	array('label'=>'List Mglist','url'=>array('index')),
	array('label'=>'Create Mglist','url'=>array('create')),
	array('label'=>'View Mglist','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Mglist','url'=>array('admin')),
);
*/
?>

<h1>Update Mglist <?php echo $model->name; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

app/protected/views/mglist/view.php
<?php
$this->breadcrumbs=array(
	'Mglists'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'Send a message','url'=>Yii::app()->createUrl("message/create", array("id"=>$model->id))),
	array('label'=>'Add a member','url'=>Yii::app()->createUrl("member/create", array("id"=>$model->id))),
	array('label'=>'Import members','url'=>Yii::app()->createUrl("member/import", array("id"=>$model->id))),
	
	array('label'=>'Update Properties','url'=>array('update','id'=>$model->id)),
	array('label'=>'Delete','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'View subscribe form','url'=>array('request/create','id'=>$model->id)),
  
);
?>

<h1>List: <?php echo $model->name; ?></h1>
<?php 

$this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'mglist-grid',
	'dataProvider'=>$membership,
	'type'=>'striped',
//	'filter'=>$membership,
	'columns'=>array(
		'member.name',
  	'member.address',
    array(            
                'name'=>'member.status',
                //call the method 'gridDataColumn' from the controller
                'value'=>array($this,'showStatus'), 
            ),
	),
)); ?>